name: zigbee2mqtt
summary: Zigbee to MQTT bridge, get rid of your proprietary Zigbee bridges
adopt-info: zigbee2mqtt
description: |
  Zigbee to MQTT bridge, get rid of your proprietary Zigbee bridges.
  Zigbee2MQTT supports various Zigbee adapters and a big bunch of devices.
  Zigbee2MQTT integrates well with most home automation solutions because it uses MQTT.
  Zigbee2MQTT is licenced under the free GNU General Public License 3.

license: GPL-3.0
confinement: strict
grade: stable
architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64

base: core22

environment:
  npm_config_prefix: "$SNAP/opt/zigbee2mqtt"
  PATH:              "$SNAP/opt/zigbee2mqtt/bin:$PATH"
  ZIGBEE2MQTT_DATA:  "$SNAP_DATA"

apps:
  zigbee2mqtt:
    command: opt/zigbee2mqtt/bin/zigbee2mqtt
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - serial-port

parts:
  zigbee2mqtt:
    after:
      - node
    plugin: nil
    build-environment:
      - PATH: "${PATH}:${CRAFT_STAGE}/opt/zigbee2mqtt/bin"
    override-build: |
      mkdir -p ${CRAFT_PART_INSTALL}/opt/zigbee2mqtt
      npm install --global --prefix ${CRAFT_PART_INSTALL}/opt/zigbee2mqtt zigbee2mqtt
      package=$(npm list --global --prefix ${CRAFT_PART_INSTALL}/opt/zigbee2mqtt | grep "── zigbee2mqtt")
      craftctl set version=${package#*@}

  node:
    plugin: nil
    stage-snaps:
      - node/20/stable
    organize:
      '*': opt/zigbee2mqtt/
    prime:
      - -opt/zigbee2mqtt/include

build-packages:
  - python3
  - python3-distutils
